export const SET_LOADING = 'SET_LOADING';
export const LOGS_ERROR = 'LOGS_ERROR';
export const GET_TOURNAMENT = 'GET_TOURNAMENT';
export const SET_CURRENT_TOURNAMENT = 'SET_CURRENT_TOURNAMENT';
export const GET_TOURNAMENTS = 'GET_TOURNAMENTS';
export const ADD_TOURNAMENT = 'ADD_TOURNAMENT';
export const GET_TOURNAMENTS_BY_USER = 'GET_TOURNAMENTS_BY_USER';
